### ISSUE TITLE
Need to update from python 3.6 to 3.9

### ISSUE THREAD

**Issue by roncewind** [Senzing/aws-lambda-self-signed-certificate#10]
AWS is ended support for Python 3.6, time to update.

**Comment by roncewind** [comment]
Hello,

We are contacting you as we have identified that your AWS Account currently has one or more Lambda functions using Python 3.6 runtime.

We are ending support for Python 3.6 in AWS Lambda. This follows Python 3.6 End-Of-Life (EOL) reached on December 23, 2021 [1].

As described in the Lambda runtime support policy [2], end of support for language runtimes in Lambda happens in two stages. Starting July 18, 2022, Lambda will no longer apply security patches and other updates to the Python 3.6 runtime used by Lambda functions, and functions using Python 3.6 will no longer be eligible for technical support. In addition, you will no longer be able to create new Lambda functions using the Python 3.6 runtime. Starting August 17, 2022, you will no longer be able to update existing functions using the Python 3.6 runtime.

We recommend that you upgrade your existing Python 3.6 functions to Python 3.9 before August 17, 2022.

End of support does not impact function execution. Your functions will continue to run. However, they will be running on an unsupported runtime which is no longer maintained or patched by the AWS Lambda team.

The following command shows how to use the AWS CLI [3] to list all functions in a specific region using Python 3.6. To find all such functions in your account, repeat this command for each region:

aws lambda list-functions --function-version ALL --region us-east-1 --output text --query "Functions[?Runtime=='python3.6'].FunctionArn"

If you have any concerns or require further assistance, please contact AWS Support [4].

[1] https://peps.python.org/pep-0494/
[2] https://docs.aws.amazon.com/lambda/latest/dg/runtime-support-policy.html
[3] https://aws.amazon.com/cli/
[4] https://aws.amazon.com/support

Sincerely,
Amazon Web Services

**Comment by docktermj** [comment]
Files have been uploaded to regional "senzing-public-xx-xxx-n" S3 buckets.

**Comment by docktermj** [comment]
Pull requests:

- https://github.com/Senzing/aws-lambda-self-signed-certificate/pull/12

**Comment by docktermj** [comment]
Reopening due to:

```console
START RequestId: f8f2f8e0-d60e-48b5-b95b-674afef304fc Version: $LATEST
[ERROR] Runtime.ImportModuleError: Unable to import module 'self_signed_certificate': No module named '_cffi_backend'
Traceback (most recent call last):
END RequestId: f8f2f8e0-d60e-48b5-b95b-674afef304fc
REPORT RequestId: f8f2f8e0-d60e-48b5-b95b-674afef304fc	Duration: 1.15 ms	Billed Duration: 2 ms	Memory Size: 128 MB	Max Memory Used: 51 MB	Init Duration: 267.74 ms	
START RequestId: f8f2f8e0-d60e-48b5-b95b-674afef304fc Version: $LATEST
[ERROR] Runtime.ImportModuleError: Unable to import module 'self_signed_certificate': No module named '_cffi_backend'
Traceback (most recent call last):
END RequestId: f8f2f8e0-d60e-48b5-b95b-674afef304fc
REPORT RequestId: f8f2f8e0-d60e-48b5-b95b-674afef304fc	Duration: 1.08 ms	Billed Duration: 2 ms	Memory Size: 128 MB	Max Memory Used: 51 MB	
START RequestId: f8f2f8e0-d60e-48b5-b95b-674afef304fc Version: $LATEST
[ERROR] Runtime.ImportModuleError: Unable to import module 'self_signed_certificate': No module named '_cffi_backend'
Traceback (most recent call last):
END RequestId: f8f2f8e0-d60e-48b5-b95b-674afef304fc
REPORT RequestId: f8f2f8e0-d60e-48b5-b95b-674afef304fc	Duration: 1.02 ms	Billed Duration: 2 ms	Memory Size: 128 MB	Max Memory Used: 51 MB	
```

**Comment by docktermj** [comment]
Pull requests:
- https://github.com/Senzing/aws-lambda-self-signed-certificate/pull/12
